### PR TITLE
fix(next): Fix options variable reuse

### PR DESCRIPTION
**Pull request by searchableguy**
I accidentally ended up reusing the options variable which is coming from the middleware so it is set and run only once which is not the intended behavior.

This fixes the behavior. 

@vvo

### CODE REVIEW

**Comment by vvo** [comment]
Hey there, can you add a test to cover this? Thanks

**Comment by searchableguy** [comment]
@vvo I added tests for both. Now I attach a random value to the request headers and use it to compute the ttl and check if it matches in the session attached. I run it twice to make sure it is new each time. 

Would that be okay?

**Comment by vvo** [comment]
All good, thanks!

**Comment by searchableguy** [comment]
Hello @vvo could you cut a new release? 😸 

I require the change in one of the application I'm working on if it's not too much to request.

**Comment by vvo** [comment]
Hey there, just did it now

**Comment by searchableguy** [comment]
Thank you so much ❤️

**Pull request merged**
