### PR TITLE
Add Sequence Diagram to README

### PR DESCRIPTION
**Pull request by snaka**
Add a sequence diagram to help understand how `Iron-session` works.

### CODE REVIEW

**Comment by snaka** [comment]
The position to add the diagram may not be appropriate, so please let me know if you have a request.

**Comment by vvo** [comment]
@snaka Would you be so kind to update the diagrams to only include app router ways of fetching data? And we would add the diagram at the end of the README, with a link at the top in the table of contents

**Comment by snaka** [comment]
@vvo 

Sorry. I've moved away from the projects using this library, so it's been difficult to catch up with the latest Next.js behaviour.

If I can afford it, I will respond, but I can't promise that for sure.

If you want, someone can respond to this, or you can close this PR.

**Comment by vvo** [comment]
That's ok @snaka thanks a lot for the initial idea!

**Pull request closed without merging**
