### PR TITLE
feat!: rewrite

### LINKED ISSUE #415: Gatsby
Hi Vincent I just wanted to let you know that the code for the next api route works just as well with the gatsby functions, so you might want to add that as a folder and to the readme. You just need to get rid of nextjs types for it to work.

### LINKED ISSUE #424: Make error more readable
I had used `process.env.COOKIE_NAME` for `cookieName` but in `.env` file, I called it `COOKIENAME` without the underscore.

This led to the same error:

> Error: iron-session: Bad usage. Minimum usage is const session = await getIronSession(req, res, { cookieName: "...", password: "...". Check the usage here: https://github.com/vvo/iron-session

It would have made sense if the error was `Error: iron-session: Bad usage. 'cookieName' or 'password' is 'undefined'` instead.

This confused me for a whole day & I wasn't able to debug the cause but it worked on other project. Finally, found the solution.

Probably a minor bug but still worth it imo :)

### LINKED ISSUE #440: withIronSessionApiRoute - API not using convention for composition (BREAKING CHANGE)
# Currently

`withIronSessionApiRoute` API is:

```ts
export function withIronSessionApiRoute(
  handler: NextApiHandler,
  options: IronSessionOptions,
): NextApiHandler {}
```

And used like this:

```ts
export default withIronSessionApiRoute(eventsRoute, sessionOptions);
```

# The issue

This means that in order to compose other decorators you'll write this:

```ts
export default withIronSessionApiRoute(withCSRF(csrfOptions)(eventsRoute), sessionOptions);
```

This is not how composition in functional programming works, which inspired both React HOCs and server decorators APIs (see https://reactjs.org/docs/higher-order-components.html#convention-maximizing-composability).

# What it should be

```ts
const withIronSessionApiRoute =
  (options: IronSessionOptions) =>
  (handler: NextApiHandler): NextApiHandler => {
    // ...    
  };
```

Then when used:

```ts
export default withIronSessionApiRoute(sessionOptions)(eventsRoute);
```

And when composed:

```ts
export default compose(
  withIronSessionApiRoute(sessionOptions),
  withCSRF(csrfOptions),
)(eventsRoute);
```

### LINKED ISSUE #442: Why is `session` only accessible from `req` and not `res`?
I guess the original idea was to attach `session` to the `req`,so you can read values from it like so:

```js
  async function getServerSideProps({ req }) {
    const user = req.session.user;
    // ...
  }
```

This makes sense.

But this makes less sense:

```js
  async function loginRoute(req, res) {
    // get user from database then:
    req.session.user = {
      id: 230,
      admin: true,
    };
    await req.session.save();
    res.send({ ok: true });
  },
```

Because this all looks as if you are mutating the request, whereas in practice you really want to mutate the response. Also, internally, `session.save()` adds `set-cookie` to the `res`, not `req`.

Note that we are saving the session on `req`, but then submit `res`. If you really pay attention, it is as if some magic happened.

For correctness sake, I think `session` should be also added to `res`, so the code above changes to:

```js
  async function loginRoute(req, res) {
    // get user from database then:
    res.session.user = {
      id: 230,
      admin: true,
    };
    await res.session.save();
    res.send({ ok: true });
  },
```

### LINKED ISSUE #455: Type error when using a baseURL and paths in a next project
I get this error when I go to build or type check with TSC on my NextJS 12 Project.
```
node_modules/iron-session/next/index.ts:8:48 - error TS2307: Cannot find module '../src/getPropertyDescriptorForReqSession' or its corresponding type declarations.

8 import getPropertyDescriptorForReqSession from "../src/getPropertyDescriptorForReqSession";
                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

in my `tsconfig.json` it looks like
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["*"]
    },
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "jsxImportSource": "@emotion/react",
    "incremental": true
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
```

If I remove these bits
```json
    "baseUrl": ".",
    "paths": {
      "@/*": ["*"]
    },
```
Works just fine but I'd really love to be able to use alias'.

Is this something that can be changed on a package side or is it just a configuration problem on my side?

### LINKED ISSUE #470: Access session in API route returning undefined but in SSR returning proper value
I am trying to get a session value but keep getting undefined when I try to get it in API Routes. Code:

Saving session:
```js
import { withSessionAPIRoute } from "../../../utils/withSession";

const handler = async (req, res) => {
  ...other code

  req.session.state = state;
  await req.session.save();

  ...other code
};

export default withSessionAPIRoute(handler);
```

Trying to retrieve it:
```js
import { withSessionAPIRoute } from "../../../utils/withSession";

const handler = async (req, res) => {
  ...other code

  console.log(req.session.state)

  ...other code
};

export default withSessionAPIRoute(handler);
```

`withSession.js`:
```js
import { withIronSessionApiRoute } from "iron-session/next";

const sessionOptions = {
  cookieName: "auth",
  password: process.env.COOKIE_SECRET,

  cookieOptions: {
    secure: process.env.NODE_ENV === "production",
    httpOnly: true,
    sameSite: "strict",
  },
};

export const withSessionAPIRoute = (handler) => {
  return withIronSessionApiRoute(handler, sessionOptions);
};
```

### LINKED ISSUE #483: Issue on on a mac not seen on my PC build.
Hi,
I have the same project building fine on my PC. Setting up and run the same project on a new Mac Pro M1 I'm running into this issue.
Not sure if it's environmental or not.  Any thoughts?

The promise rejected with the reason:
Error: iron-session: Bad usage. Minimum usage is const session = await getIronSession(req, res, { cookieName: "...", password: "...". Check the usage here: https://github.com/vvo/iron-session

### LINKED ISSUE #498: Getting bad usage,  Minimum usage is const session = await getIronSession(...)
I'm using iron-session/next in my login api route I'm getting this error whenever I try logging in.

This is the code I'm using

```
import type { NextApiRequest, NextApiResponse } from "next";
import query from "../../lib/db";
import bcrypt from "bcrypt";
import { withIronSessionApiRoute } from "iron-session/next";
import { sessionOptions } from "../../lib/session";

export default withIronSessionApiRoute(loginRoute, sessionOptions);

async function loginRoute(req: NextApiRequest, res: NextApiResponse) {
  if (req.method === "POST") {
    try {
      const user: any = await query({
        query: "SELECT * FROM users WHERE email=?",
        values: [req.body.email],
      });

      const isMatched = await bcrypt.compare(
        req.body.password,
        user[0].password.replace("$2y$", "$2a$")
      );

      if (!isMatched)
        res
          .status(400)
          .json({ message: "Invalid Credentials, Please try again." });

      if (user.length === 0)
        res.status(401).json({ message: "User is not found" });

      req.session.user = user;
      await req.session.save();

      res.status(200).json({ ok: true });
    } catch (error) {
      res.status(500).json({ message: (error as Error).message });
    }
  }
}
```

### LINKED ISSUE #503: withIronSessionSSr GetServerSidePropsContext could use a params type
Here you can see that params should extend `ParsedUrlQuery`:
```ts
export type GetServerSidePropsContext<
  Q extends ParsedUrlQuery = ParsedUrlQuery,
  D extends PreviewData = PreviewData
> = {
 ...
  params?: Q
  ...
}
```
However, you can see that there's no generic passed to `context: GetServerSidePropsContext` here:
```ts
declare function withIronSessionSsr<P extends {
    [key: string]: unknown;
} = {
    [key: string]: unknown;
}>(handler: (context: GetServerSidePropsContext) => GetServerSidePropsResult<P> | Promise<GetServerSidePropsResult<P>>, options: IronSessionOptions | GetIronSessionSSROptions): (context: GetServerSidePropsContext) => Promise<GetServerSidePropsResult<P>>;
```
So when I do this, params doesn't 
```ts
export const getServerSideProps: GetServerSideProps = withIronSessionSsr(
  async ({ req, res: _, params, query }) => {
```

### LINKED ISSUE #514: Can't infer prop types from session wrapper
Hey! I'm using your utility with Next.js and [a session wrapper from advanced usage](https://github.com/vvo/iron-session#session-wrappers) (TypeScript). And then when I try to infer prop types from my getServerSideProps, it won't work. 
Here some screenshots:
`shared/lib/session.ts`
image
`pages/index.tsx`
image
`pages/index.tsx`
image

Every prop on *Image 3* is of type unknown or any type that I will set in the wrapper on *Image 1*
I'm also not a pro with TypeScript so I couldn't think of something by myself. Any ideas on how to fix this?

### LINKED ISSUE #518: Cannot create session
Hi there, I'm trying to **create** a session within an API, currently I have
```
req.session.user = {
          isLoggedIn: true,
          userId: response.data.id,
          username: response.data.username,
          discriminator: response.data.discriminator,
          avatar: response.data.avatar,
          email: response.data.email,
          access_token: accessdata.access_token,
       };
          await req.session.save();
```

Although I continue to get the following error:
`TypeError: Cannot set properties of undefined (setting 'user')`

### LINKED ISSUE #532: Idea: remove withIronSessionApiRoute, withIronSessionSsr and only keep getIronSession
With the introduction of `getIronSession(req, res, options)` in https://github.com/vvo/iron-session/pull/510, knowing all the weird issues people are bumping into when using withIronSessionApiRoute, withIronSessionSsr (especially TS ones). I propose to remove all apis and only keep getIronSession. Then we can let folks write wrappers themselves, and explain them how to do it if that makes sense.

This would drastically reduce our API surface.

Thoughts @brc-dd?

### LINKED ISSUE #554: nextjs server components update
Nextjs server components has a different api from both serversideProps, middleware and api routes. I made a first working version to get the user, but no version of the save and destroy version yet. I'm just leaving this here in case anyone wants to use it and it might be used in a more complete form as a pull request later.

```typescript
// import crypto from "crypto"; (todo: check if this is the right crypto, edge nodejs etc..)
// import { createUnsealData } from "iron-session";
// import { cookies } from "next/headers";
const getUser = async ({
  password,
  cookieName,
}: {
  password: string;
  cookieName: string;
}) => {
  const nextCookies = cookies();
  const cookie = nextCookies.get(cookieName);

  const unsealData = createUnsealData(crypto);
  const sess =
    cookie === undefined
      ? {}
      : await unsealData(cookie, {
          password: { 1: password },
        });
  return sess as unknown as { user: IronSession["user"] };
};
```

### LINKED ISSUE #559: Type error: Property 'session' does not exist on type 'IronSession'.
IronSession in middleware Failed to compile for VERCEL.
image

./middleware.ts:11:11 
Type error: Property 'session' does not exist on type 'IronSession'. 
 > 9 | export const middleware = async (req: NextRequest) => { 
> 10 | const res = NextResponse.next();
> 11 | const { session } = await getIronSession(req, res, ironSessionOptions); 
> | ^ 
> 12 | 
> 13 | if ( 
> 14 | req.nextUrl.pathname.startsWith("/projects") ||
Error: Command "npm run build" exited with 1

On other places I used `import { getIronSession } from "iron-session`
but as node API is not supported on edge runtime, documentations guides to import `import { getIronSession } from "iron-session/edge";`

code for middleware is:
`import { getIronSession } from "iron-session/edge";`
`import { ironSessionOptions } from "./lib/config";`

`export const middleware = async (req: NextRequest) => {`
`  const res = NextResponse.next();`
`  const { session } = await getIronSession(req, res, ironSessionOptions);`  <<< Error Occurs Here ( session does not exist on 'iron-session/edge' but exists on 'iron-session' )
`return res;`
`}`

### LINKED ISSUE #560: Support for next js 13 server side components
The old `getServerSideProps` api is deprecated, and you no longer have access to the request and response objects. Instead you get access to [headers and cookies](https://beta.nextjs.org/docs/upgrade-guide#accessing-request-object).

It would be nice to have a new helper function like `withIronSessionSsr` for accessing the session in server side components.

### LINKED ISSUE #567: getIronSession with graphql-yoga context
I'm creating graphql server with `graphql-yoga` in nextjs application. In my `pages/api/graphql.ts` I have the following code :
``` 
import prisma from "@lib/prisma";
import { schema } from "src/graphql/schema";
import { sessionOptions } from "@lib/session";
import { getIronSession } from "iron-session/edge";

export default createYoga({
  schema,
  // Needed to be defined explicitly because our endpoint lives at a different path other than `/graphql`
  graphqlEndpoint: "/api/graphql",
  context: async ({req, res})=>{
     const session = await getIronSession(req, res, sessionOptions);
     if(!session) return {prisma}
     return {prisma, user:session.user}
   }
});
```

when running the server and head to graphql playground by yoga on `localhost:3000/api/graphql`, I get the following error:
`Server Error
Error: no native implementation of WebCrypto is available in current context`

I can't seem to find anything to help with this. if I commented out the line that make use of `getIronSession` everything seems to work fine.

### LINKED ISSUE #568: unhandledRejection: TypeError: argument name is invalid
why is this？
image

### LINKED ISSUE #569: Next.js 13 app directory support
Hi devs, first off, thanks for all the work on this project! 

I am giving Next 13 a shot. Since `getServerSideProps` cannot be used in Server Side Components in the `app` directory, is there a recommended way to make `getIronSession` work in such components?

### LINKED ISSUE #570: Next.js 13.2 new route.js support (app directory)
I realize this is bleeding edge as this won't even be released until Next 13.2, but just wanted to get the ball rolling ahead of time.

Currently, I don't see a way you can use `iron-session` with the upcoming [route.js](https://beta.nextjs.org/docs/api-reference/file-conventions/route) architecture.

My current implementation of `iron-session` uses `withIronSessionApiRoute` which requires a `handler: NextApiHandler`. This works for now, however, this is being removed in favor of a more generic `request: Request` when the `pages` directory goes away in favor of the `app` directory.

Thanks!

### LINKED ISSUE #571: IronSession.destroy() return type should be a Promise
The index.d.ts file inside the dist folder contains the type declaration 
```typescript
declare type IronSession = IronSessionData & {
    /**
     * Destroys the session data and removes the cookie.
     */
    destroy: () => void;
    /**
     * Encrypts the session data and sets the cookie.
     */
    save: () => Promise<void>;
};
```
The type of save() should return a promise as well, as the session will not be destroyed if the function is not awaited.
*Version:* 6.3.1

### LINKED ISSUE #572: withIronSessionSsr doesn't support params generic
withIronSessionSsr supports the props generic, but doesn't allow you to pass a custom params type to GetServerSidePropsContext

### PR DESCRIPTION
**Pull request by brc-dd**
### Highlights

* Support for Next.js App Dir (Routes + RSC)
* Cleaner API (wrappers are removed)
* Fully framework agnostic (no /next, /edge, /express sub-exports)
* Supports Node.js (16, 18, 19), Deno and Bun
* Better TS support (uses generics instead of module augmentation)
* More clear error messages

### Linked Issues

- [x] closes #532
- [x] closes #572
- [x] closes #571
- [x] closes #570
- [x] closes #569
- [x] closes #568
- [x] closes #567
- [x] closes #565
- [x] closes #563
- [x] closes #560
- [x] closes #559
- [x] closes #554
- [x] closes #548
- [x] closes #518
- [x] closes #514
- [x] closes #509
- [x] closes #503
- [x] closes #498
- [x] closes #483
- [x] closes #470
- [x] closes #456
- [x] closes #455
- [x] closes #449
- [x] closes #442
- [x] closes #440
- [x] closes #424
- [x] closes #415
- [ ] #562
- [ ] #521
- [ ] #437

Some of these issues are marked for closing simply because we are removing the wrappers. Some feature requests are closed because we are going forward with more cleaner and framework agnostic API.

### TODO

- [ ] docs
- [ ] examples
- [ ] tests
- [ ] CI
- [ ] all contributors, renovate, etc.

### CODE REVIEW

**Comment by trevoro** [comment]
@brc-dd Are you the new maintainer of `iron-session` ?

**Comment by brc-dd** [comment]
@trevoro Vincent is still active, but he is busy shipping cool features at Vercel. So I'm just doing the heavy lifting to keep the library alive and up to date. Yeah, I do have write and publish access though 😅

**Comment by trevoro** [comment]
@brc-dd Cool. I have an interest in making `iron-session` the best example on how to do good authentication in next. This rewrite seems like quite the undertaking! Do you have any kind of rough ETA on getting an alpha release put together that we can start hammering on as a community?

**Comment by brc-dd** [comment]
@trevoro I think we can merge this and release a version under `alpha` tag once docs and tests are done. The examples can then be community led.

**Comment by trevoro** [comment]
@brc-dd If I can make a suggestion; would you consider adding an alpha tag without the tests? I'm not suggesting a release or NPM publish just making it easier to merge to a branch that can be used as the 'master' v2 branch instead of merging to a WIP branch. So something like merging or renaming this branch to `2.0.0-alpha`, merging this PR, and continuing the rest of the work in smaller increments. That makes it easier for people to contribute.

**Comment by brc-dd** [comment]
Hey sorry got occupied in some work these few months. Created a new v7 branch and merged this. Feel free to contribute there. Also created a roadmap issue (#586) to track things. Hopefully, we will release v7 stable around the time app router reaches RC/stable.

**Comment by KBeDevel** [comment]
Foremost, thank you for your amazing work @brc-dd.

After see the [NPM package page](https://www.npmjs.com/package/iron-session?activeTab=versions), I noticed version 7.0.0-7.0.6 versions were published around a year ago. IDK if this project is strictly using semantic versioning, I suppose those versions are some kind of unexpected release (?).

I suggest doing one of the following:

1. Jump to the next release version, in this case (for NPM versioning consistency), the 8th release.
2. Publish the package under another NPM name (for example: `@iron-session/...`, `@iron/session`, `@vvo/iron-session`, etc.).

Other (rare) alternatives are:

1. Use a minor release tag (7.**x**.y), which is a bit confusing and is not semantic version compatible.
2. Publish 7.x.y and 8.x.y at the same time.
3. Republish the package.

Hope this helps

**Comment by brc-dd** [comment]
@KBeDevel This PR isn't released on npm yet. Working is still going on a separate branch. Those published v7 versions don't work and no one uses them. We probably can deprecated them (unpublish won't work). Will publish the new version as v8.

**Pull request merged**
